#!/usr/bin/env python3
"""
Report Generator - recon-dominator
Consolidates all recon data into a unified report.
Author: maeitsec
"""

import argparse
import json
import glob
from pathlib import Path
from datetime import datetime


def log(msg):
    print(f"[*] {msg}")


def success(msg):
    print(f"[+] {msg}")


def warn(msg):
    print(f"[!] {msg}")


def load_json(filepath):
    """Safely load a JSON file."""
    try:
        with open(filepath) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        warn(f"Could not load {filepath}: {e}")
        return None


def generate_markdown_report(data, domain):
    """Generate human-readable Markdown report."""
    lines = []
    lines.append(f"# Reconnaissance Report: {domain}")
    lines.append(f"")
    lines.append(f"**Generated by:** recon-dominator (orizon.one)")
    lines.append(f"**Date:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Classification:** CONFIDENTIAL - Authorized Personnel Only")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"")

    # Executive Summary
    lines.append(f"## Executive Summary")
    lines.append(f"")

    passive = data.get("passive_recon")
    active = data.get("active_recon")
    ports = data.get("port_scan")
    tech = data.get("tech_fingerprint")
    osint = data.get("osint")
    wayback = data.get("wayback")
    dorks = data.get("dorking")

    total_subs = 0
    if passive:
        total_subs += passive.get("meta", {}).get("total_unique", 0)
    if active:
        total_subs += active.get("meta", {}).get("total_unique", 0)

    live_hosts = ports.get("meta", {}).get("live_hosts", 0) if ports else 0
    open_ports = ports.get("meta", {}).get("total_open_ports", 0) if ports else 0
    techs = len(tech.get("technology_summary", [])) if tech else 0

    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Subdomains Discovered | {total_subs} |")
    lines.append(f"| Live Hosts | {live_hosts} |")
    lines.append(f"| Open Ports | {open_ports} |")
    lines.append(f"| Unique Technologies | {techs} |")
    lines.append(f"")

    # Subdomains
    if passive or active:
        lines.append(f"## Subdomains")
        lines.append(f"")
        if passive:
            lines.append(f"### Passive Enumeration")
            lines.append(f"")
            for sub in passive.get("subdomains", [])[:100]:
                sources = ", ".join(sub.get("sources", []))
                lines.append(f"- `{sub['host']}` ({sources})")
            if len(passive.get("subdomains", [])) > 100:
                lines.append(f"- ... and {len(passive['subdomains']) - 100} more")
            lines.append(f"")

        if active:
            lines.append(f"### Active Enumeration")
            lines.append(f"")
            for sub in active.get("subdomains", [])[:100]:
                ips = ", ".join(sub.get("ips", []))
                lines.append(f"- `{sub['host']}` -> {ips}")
            lines.append(f"")

    # Port Scan Results
    if ports and ports.get("results"):
        lines.append(f"## Open Ports and Services")
        lines.append(f"")
        lines.append(f"| Host | IP | Open Ports | WAF/CDN |")
        lines.append(f"|------|-----|-----------|---------|")
        for r in ports["results"][:50]:
            port_list = ", ".join(str(p["port"]) for p in r.get("open_ports", []))
            waf = r.get("waf_cdn", "none")
            lines.append(f"| `{r['host']}` | {r.get('ip', '')} | {port_list} | {waf} |")
        lines.append(f"")

    # Technology Stack
    if tech and tech.get("results"):
        lines.append(f"## Technology Stack")
        lines.append(f"")
        for r in tech["results"][:50]:
            if r["technologies"]:
                lines.append(f"### {r['host']}")
                lines.append(f"")
                for t in r["technologies"]:
                    lines.append(f"- {t}")
                # Security headers
                details = r.get("details", {})
                missing = details.get("missing_security_headers", [])
                if missing:
                    lines.append(f"- **Missing security headers:** {', '.join(missing)}")
                lines.append(f"")

    # OSINT
    if osint:
        lines.append(f"## OSINT Intelligence")
        lines.append(f"")

        whois = osint.get("whois", {})
        if whois:
            lines.append(f"### WHOIS")
            lines.append(f"- **Registrar:** {whois.get('registrar', 'N/A')}")
            lines.append(f"- **Created:** {whois.get('creation_date', 'N/A')}")
            lines.append(f"- **Organization:** {whois.get('registrant_org', 'N/A')}")
            lines.append(f"")

        asn = osint.get("asn", {})
        if asn:
            lines.append(f"### Network")
            lines.append(f"- **ASN:** {asn.get('as', 'N/A')}")
            lines.append(f"- **Organization:** {asn.get('org', 'N/A')}")
            lines.append(f"- **ISP:** {asn.get('isp', 'N/A')}")
            lines.append(f"- **Location:** {asn.get('city', '')}, {asn.get('country', '')}")
            lines.append(f"")

        email = osint.get("email", {})
        if email:
            lines.append(f"### Email")
            lines.append(f"- **Provider:** {email.get('email_provider', 'N/A')}")
            lines.append(f"")

        reverse = osint.get("reverse_ip", {})
        if reverse and reverse.get("shared_domains"):
            lines.append(f"### Shared Hosting ({reverse['count']} domains on same IP)")
            for d in reverse["shared_domains"][:20]:
                lines.append(f"- `{d}`")
            lines.append(f"")

    # Wayback
    if wayback:
        stats = wayback.get("stats", {})
        lines.append(f"## Wayback Machine Analysis")
        lines.append(f"")
        lines.append(f"| Category | Count |")
        lines.append(f"|----------|-------|")
        lines.append(f"| Total Archived URLs | {stats.get('total_urls', 0)} |")
        lines.append(f"| API Endpoints | {stats.get('api_endpoints', 0)} |")
        lines.append(f"| JavaScript Files | {stats.get('js_files', 0)} |")
        lines.append(f"| Config/Sensitive Files | {stats.get('config_files', 0)} |")
        lines.append(f"| Admin Panels | {stats.get('admin_panels', 0)} |")
        lines.append(f"| Removed Content | {stats.get('removed_pages', 0)} |")
        lines.append(f"")

        params = wayback.get("parameters", {})
        top_params = params.get("top_parameters", [])[:10]
        if top_params:
            lines.append(f"### Top Parameters (Potential Injection Points)")
            lines.append(f"")
            for p in top_params:
                lines.append(f"- `{p['name']}` ({p['occurrences']} occurrences)")
            lines.append(f"")

    # Recommendations
    lines.append(f"## Recommended Next Steps")
    lines.append(f"")
    lines.append(f"1. **Vulnerability scanning** on all live hosts with open web ports")
    lines.append(f"2. **API testing** on discovered API endpoints")
    lines.append(f"3. **Cloud pivot analysis** on cloud-hosted assets")
    lines.append(f"4. **Manual review** of Google dork results and Wayback removed content")
    lines.append(f"5. **Credential checking** on exposed panels and login pages")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"*Report generated by recon-dominator | orizon.one*")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Report Generator - orizon.one")
    parser.add_argument("--project", "-p", required=True, help="Project name / output directory")
    parser.add_argument("--domain", "-d", required=True, help="Primary target domain")
    parser.add_argument("--data-dir", help="Directory with JSON result files (default: current dir)")
    args = parser.parse_args()

    domain = args.domain.strip().lower().rstrip(".")
    data_dir = Path(args.data_dir) if args.data_dir else Path(".")
    output_dir = Path(args.project)
    output_dir.mkdir(parents=True, exist_ok=True)

    log(f"Generating consolidated report for: {domain}")

    # Load all available data
    domain_slug = domain.replace(".", "_")
    data = {}

    file_mapping = {
        "passive_recon": f"passive_recon_{domain_slug}.json",
        "active_recon": f"active_recon_{domain_slug}.json",
        "port_scan": "port_scan_results.json",
        "tech_fingerprint": "tech_fingerprint_results.json",
        "osint": f"osint_{domain_slug}.json",
        "wayback": f"wayback_{domain_slug}.json",
        "dorking": f"dorks_{domain_slug}.json",
    }

    for key, filename in file_mapping.items():
        filepath = data_dir / filename
        loaded = load_json(filepath)
        if loaded:
            data[key] = loaded
            success(f"Loaded: {filename}")
        else:
            log(f"Not found: {filename} (skipping)")

    if not data:
        warn("No data files found. Run the recon modules first.")
        return

    # Generate Markdown report
    report_md = generate_markdown_report(data, domain)
    report_path = output_dir / "summary.md"
    report_path.write_text(report_md)
    success(f"Markdown report: {report_path}")

    # Copy/consolidate JSON data
    consolidated = {
        "meta": {
            "domain": domain,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "type": "consolidated_report",
            "tool": "recon-dominator by orizon.one",
            "modules_loaded": list(data.keys())
        },
        "data": data
    }

    consolidated_path = output_dir / "consolidated.json"
    with open(consolidated_path, "w") as f:
        json.dump(consolidated, f, indent=2)
    success(f"Consolidated JSON: {consolidated_path}")

    # Summary
    print(f"\n{'='*60}")
    print(f"  REPORT GENERATED - {domain}")
    print(f"{'='*60}")
    print(f"  Output directory : {output_dir}")
    print(f"  Markdown report  : {report_path}")
    print(f"  JSON data        : {consolidated_path}")
    print(f"  Modules included : {', '.join(data.keys())}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
